CREATE TABLE IF NOT EXISTS cards (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    card_set_id VARCHAR(30) NOT NULL UNIQUE,
    card_name VARCHAR(255) NOT NULL,
    set_name VARCHAR(255) NOT NULL,
    set_id VARCHAR(20) NOT NULL,
    rarity VARCHAR(10) NOT NULL,
    card_color VARCHAR(50) NOT NULL,
    card_type VARCHAR(50) NOT NULL,
    card_power VARCHAR(20) NULL,
    card_cost VARCHAR(10) NULL,
    life VARCHAR(10) NULL,
    sub_types VARCHAR(255) NULL,
    counter_amount VARCHAR(10) NULL,
    attribute VARCHAR(50) NULL,
    card_text TEXT NULL,
    card_image_url VARCHAR(500) NULL,
    market_price DECIMAL(10,2) NULL,
    inventory_price DECIMAL(10,2) NULL,
    is_parallel TINYINT(1) NOT NULL DEFAULT 0,
    last_synced_at TIMESTAMP NULL,
    INDEX idx_set_id (set_id),
    INDEX idx_card_name (card_name),
    INDEX idx_rarity (rarity),
    INDEX idx_card_color (card_color),
    INDEX idx_card_type (card_type),
    INDEX idx_market_price (market_price)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
