CREATE TABLE IF NOT EXISTS marketplace_listings (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    seller_id INT UNSIGNED NOT NULL,
    card_id INT UNSIGNED NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT NULL,
    `condition` ENUM('NM','LP','MP','HP','DMG') NOT NULL DEFAULT 'NM',
    price DECIMAL(10,2) NOT NULL,
    quantity INT UNSIGNED NOT NULL DEFAULT 1,
    quantity_sold INT UNSIGNED NOT NULL DEFAULT 0,
    shipping_from_country CHAR(2) NULL,
    shipping_cost DECIMAL(8,2) NOT NULL DEFAULT 0.00,
    ships_internationally TINYINT(1) NOT NULL DEFAULT 0,
    status ENUM('active','sold','cancelled','expired') NOT NULL DEFAULT 'active',
    images JSON NULL,
    views_count INT UNSIGNED NOT NULL DEFAULT 0,
    expires_at TIMESTAMP NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_seller_id (seller_id),
    INDEX idx_card_id (card_id),
    INDEX idx_status (status),
    INDEX idx_price (price),
    INDEX idx_condition (`condition`),
    INDEX idx_card_status_price (card_id, status, price),
    INDEX idx_created (created_at),
    INDEX idx_expires (expires_at),
    FOREIGN KEY (seller_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (card_id) REFERENCES cards(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
